modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="better_respawn"
version="1.0.0"
displayName="Better Respawn"
displayURL="https://prcrichards.wixsite.com/portfolio"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Die in style."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.better_respawn]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.better_respawn]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




[[mixins]]
    config="mixins.better_respawn.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration